services:  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      # - KC_SSL_ENABLED=true  # Enable SSL
      # - KC_HTTP_PORT=8443  # Change HTTP port to 8443 for SSL
    ports:
      - "8080:8080"
    command: start-dev
    networks:
      - keycloak-network
     
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      - LDAP_ORGANISATION="MyCompany Inc."
      - LDAP_DOMAIN=mycompany.com
    ports:
      - "389:389"
    networks:
      - keycloak-network
      
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    ports:
      - "10080:80"
      - "10443:443"
    depends_on:
      - openldap
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge